### ISSUE TITLE
Deleted some functionality

### ISSUE THREAD

**Issue by thestick613** [sourceryai/public#14] opened 2019-08-30 21:04 UTC
Hello, i have tried this out and it looks pretty nice, but this obviously is wrong:
```
         del fields["full_name"]
-    elif "full_name" in fields and ("first_name" in fields or "last_name" in fields):
+    elif "full_name" in fields:
         raise Exception(

```

**Comment by Hellebore** [comment] 2019-08-30 21:29
Hi - are you able to provide any more context of the code above this snippet? It will help me to reproduce the issue.

**Comment by thestick613** [comment] 2019-08-30 21:32
On second thought, it might be correct, but it's as confusing as the original code..
```
    if "full_name" in fields and "first_name" not in fields and "last_name" not in fields:
        # do some stuff
    elif "full_name" in fields and ("first_name" in fields or "last_name" in fields):
        # do some other stuff

```

**Comment by Hellebore** [comment] 2019-08-30 21:58
Yes it looks like it's determined that the condition is always true at that point so it can be removed (which I think is true).

We aim to make the code simpler as far as we can - is there something you'd prefer Sourcery to do in this instance?

**Comment by thestick613** [comment] 2019-08-30 22:04
Not sure, i have to think it out a bit. I noticed sourcery doesn't like nested if's, but that's what i would do here, for more clarity.
```
    if "full_name" in fields:
        if "first_name" not in fields and "last_name" not in fields:
            # do some stuff
        else:
            # do some other stuff
```

**Comment by Hellebore** [comment] 2019-10-15 14:40
Addressed in next release.

**Closed by Hellebore** 2019-10-15 14:40 UTC
